This is makeindex, version 2.17 [TeX Live 2024] (kpathsea + Thai support).
Scanning style file ./mainPart.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file mainPart.acn....done (12 entries accepted, 0 rejected).
Sorting entries....done (44 comparisons).
Generating output file mainPart.acr....done (30 lines written, 0 warnings).
Output written in mainPart.acr.
Transcript written in mainPart.alg.
